src/modules/temperature/FSI_temperatureConverter.c File Reference
#include <string.h>
#include "../../../inc/fsi/modules/temperature/FSI_temperatureConverter.h"
Functions
double FSI_temperatureConvertCelFrom (const char *to, const double from)
Convert from from to Celcius as a double.
double FSI_temperatureConvertCelTo (const char *from, const double to)
Convert Celcius to from as a double.
Function Documentation
FSI_temperatureConvertCelFrom()
double FSI_temperatureConvertCelFrom (const char * to, const double from)
Convert from from to Celcius as a double.
Parameters
from The value of the temperature
to From celcius to the temperature
Returns
The exact converted temperature
Definition at line 5 of file FSI_temperatureConverter.c.
{
    if (strlen(to) >= 0 || strlen(to) >= 1)
    {
        if (to[0] == 'c')
            return __FSI_TC_CEL_FROM_C(from);
        else if (to[0] == 'f')
            return __FSI_TC_CEL_FROM_F(from);
        else if (to[0] == 'k')
            return __FSI_TC_CEL_FROM_K(from);
        else if (to[0] == 'r' && to[1] == 'e')
            return __FSI_TC_CEL_FROM_RE(from);
        else if (to[0] == 'r' && to[1] == 'a')
            return __FSI_TC_CEL_FROM_RA(from);
    }
    return 0;
}
References __FSI_TC_CEL_FROM_C, __FSI_TC_CEL_FROM_F, __FSI_TC_CEL_FROM_K, __FSI_TC_CEL_FROM_RA, and __FSI_TC_CEL_FROM_RE.
Referenced by fsi::modules::tc::convertFrom(), and main().
FSI_temperatureConvertCelTo()
double FSI_temperatureConvertCelTo (const char * from, const double to)
Convert Celcius to from as a double.
Parameters
from Convert to from celcius
to The value of the temperature
Returns
The exact converted temperature
Definition at line 31 of file FSI_temperatureConverter.c.
{
    if (strlen(from) >= 0 || strlen(from) >= 1)
    {
        if (from[0] == 'c')
            return __FSI_TC_CEL_TO_C(to);
        else if (from[0] == 'f')
            return __FSI_TC_CEL_TO_F(to);
        else if (from[0] == 'k')
            return __FSI_TC_CEL_TO_K(to);
        else if (from[0] == 'r' && from[1] == 'e')
            return __FSI_TC_CEL_TO_RE(to);
        else if (from[0] == 'r' && from[1] == 'a')
            return __FSI_TC_CEL_TO_RA(to);
    }
    return 0;
}
References __FSI_TC_CEL_TO_C, __FSI_TC_CEL_TO_F, __FSI_TC_CEL_TO_K, __FSI_TC_CEL_TO_RA, and __FSI_TC_CEL_TO_RE.
Referenced by fsi::modules::tc::convertTo(), and main().