.TH "src/ARGXAddError.cpp" 3 "Version 1.0.0-build" "Argx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ARGXAddError.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <utility>\fP
.br
\fR#include <string>\fP
.br
\fR#include '\&.\&./inc/ARGXAddError\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBargx\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Argx from the source code\&.
