.TH "src/Argx.cpp" 3 "Version 1.2.0-beta" "Argx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Argx.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <codecvt>\fP
.br
\fR#include <locale>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include '\&.\&./inc/Argx\&.hpp'\fP
.br
\fR#include '\&.\&./inc/types\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBargx\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Argx from the source code\&.
