.TH "argx::ARGXParam" 3 "Version 1.1.0-build" "Argx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
argx::ARGXParam
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <types\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBexists\fP = false"
.br
.ti -1c
.RI "std::vector< bool > \fBsubExists\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB49\fP of file \fBtypes\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool argx::ARGXParam::exists = false"

.PP
Definition at line \fB51\fP of file \fBtypes\&.hpp\fP\&.
.PP
Referenced by \fBargx::Argx::getParam()\fP\&.
.SS "std::vector<bool> argx::ARGXParam::subExists"

.PP
Definition at line \fB52\fP of file \fBtypes\&.hpp\fP\&.
.PP
Referenced by \fBargx::Argx::getParam()\fP, and \fBargx::Argx::getSubParam()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Argx from the source code\&.
