.TH "inc/ARGXAddError.hpp" 3 "Version 1.0.0-build" "Argx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/ARGXAddError.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <utility>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBargx::ARGXAddError\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBargx\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Argx from the source code\&.
