.TH "argx" 3 "Version 1.2.2-build" "Argx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
argx
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArgx\fP"
.br
.ti -1c
.RI "class \fBARGXAddError\fP"
.br
.ti -1c
.RI "struct \fBARGXError\fP"
.br
.ti -1c
.RI "struct \fBARGXOptions\fP"
.br
.ti -1c
.RI "struct \fBARGXParam\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct argx::ARGXError \fBARGXError\fP"
.br
.ti -1c
.RI "typedef struct argx::ARGXOptions \fBARGXOptions\fP"
.br
.ti -1c
.RI "typedef struct argx::ARGXParam \fBARGXParam\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBARGXStyle\fP { \fBProfessional\fP, \fBSimple\fP }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct argx::ARGXError argx::ARGXError"

.SS "typedef struct argx::ARGXOptions argx::ARGXOptions"

.SS "typedef struct argx::ARGXParam argx::ARGXParam"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBargx::ARGXStyle\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIProfessional \fP
.TP
\f(BISimple \fP
.PP
Definition at line \fB9\fP of file \fBtypes\&.hpp\fP\&.
.nf
10     {
11         Professional,
12         Simple,
13     };
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Argx from the source code\&.
