.TH "argx::ARGXOptions" 3 "Version 0.1.0-beta" "Argx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
argx::ARGXOptions
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <types\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBhasSubParams\fP = false"
.br
.ti -1c
.RI "std::string \fBid\fP"
.br
.RI "ID (id) "
.ti -1c
.RI "std::string \fBinfo\fP"
.br
.ti -1c
.RI "std::string \fBparam\fP"
.br
.RI "Param (param): "
.ti -1c
.RI "std::string \fBsparam\fP"
.br
.RI "Short Param (sparam): "
.ti -1c
.RI "std::vector< \fBARGXOptions\fP > \fBsubParams\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB24\fP of file \fBtypes\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool argx::ARGXOptions::hasSubParams = false"

.PP
Definition at line \fB43\fP of file \fBtypes\&.hpp\fP\&.
.SS "std::string argx::ARGXOptions::id"

.PP
ID (id) ID of the option 
.PP
Definition at line \fB29\fP of file \fBtypes\&.hpp\fP\&.
.SS "std::string argx::ARGXOptions::info"

.PP
Definition at line \fB41\fP of file \fBtypes\&.hpp\fP\&.
.SS "std::string argx::ARGXOptions::param"

.PP
Param (param): EXAMPLE: --help, --version 
.PP
Definition at line \fB35\fP of file \fBtypes\&.hpp\fP\&.
.SS "std::string argx::ARGXOptions::sparam"

.PP
Short Param (sparam): 
.PP
Definition at line \fB40\fP of file \fBtypes\&.hpp\fP\&.
.SS "std::vector<\fBARGXOptions\fP> argx::ARGXOptions::subParams"

.PP
Definition at line \fB45\fP of file \fBtypes\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Argx from the source code\&.
