.TH "argx::ARGXOptions" 3 "Version 1.2.2-build" "Argx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
argx::ARGXOptions
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <types\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBdefaultValue\fP"
.br
.ti -1c
.RI "bool \fBhasAnySubParams\fP = false"
.br
.ti -1c
.RI "bool \fBhasSubParams\fP = false"
.br
.ti -1c
.RI "std::string \fBid\fP"
.br
.RI "ID (id) "
.ti -1c
.RI "std::string \fBinfo\fP"
.br
.ti -1c
.RI "std::string \fBparam\fP"
.br
.RI "Param (param)\&. "
.ti -1c
.RI "bool \fBrequired\fP = false"
.br
.ti -1c
.RI "std::string \fBsparam\fP"
.br
.RI "Short Param (sparam): "
.ti -1c
.RI "std::vector< \fBARGXOptions\fP > \fBsubParams\fP"
.br
.ti -1c
.RI "std::string \fBtag\fP = 'default'"
.br
.RI "Set default tag to categorize arguments\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB25\fP of file \fBtypes\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string argx::ARGXOptions::defaultValue"

.PP
Definition at line \fB48\fP of file \fBtypes\&.hpp\fP\&.
.PP
Referenced by \fBargx::Argx::getSubValue()\fP\&.
.SS "bool argx::ARGXOptions::hasAnySubParams = false"

.PP
Definition at line \fB51\fP of file \fBtypes\&.hpp\fP\&.
.PP
Referenced by \fBargx::Argx::compareArgs()\fP, and \fBargx::Argx::getWrongArgs()\fP\&.
.SS "bool argx::ARGXOptions::hasSubParams = false"

.PP
Definition at line \fB50\fP of file \fBtypes\&.hpp\fP\&.
.PP
Referenced by \fBargx::Argx::compareArgs()\fP, and \fBargx::Argx::getWrongArgs()\fP\&.
.SS "std::string argx::ARGXOptions::id"

.PP
ID (id) ID of the option 
.PP
Definition at line \fB30\fP of file \fBtypes\&.hpp\fP\&.
.SS "std::string argx::ARGXOptions::info"

.PP
Definition at line \fB42\fP of file \fBtypes\&.hpp\fP\&.
.SS "std::string argx::ARGXOptions::param"

.PP
Param (param)\&. EXAMPLE: --help, --version 
.PP
Definition at line \fB36\fP of file \fBtypes\&.hpp\fP\&.
.PP
Referenced by \fBargx::Argx::getArgIDPos()\fP\&.
.SS "bool argx::ARGXOptions::required = false"

.PP
Definition at line \fB52\fP of file \fBtypes\&.hpp\fP\&.
.SS "std::string argx::ARGXOptions::sparam"

.PP
Short Param (sparam): 
.PP
Definition at line \fB41\fP of file \fBtypes\&.hpp\fP\&.
.PP
Referenced by \fBargx::Argx::getArgIDPos()\fP\&.
.SS "std::vector<\fBARGXOptions\fP> argx::ARGXOptions::subParams"

.PP
Definition at line \fB54\fP of file \fBtypes\&.hpp\fP\&.
.PP
Referenced by \fBargx::Argx::compareArgs()\fP, and \fBargx::Argx::getWrongArgs()\fP\&.
.SS "std::string argx::ARGXOptions::tag = 'default'"

.PP
Set default tag to categorize arguments\&. 
.PP
Definition at line \fB47\fP of file \fBtypes\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Argx from the source code\&.
