.TH "argx::ARGXError" 3 "Version 1.0.0-build" "Argx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
argx::ARGXError
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <types\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcode\fP"
.br
.ti -1c
.RI "std::string \fBerror\fP"
.br
.ti -1c
.RI "std::string \fBhelp\fP"
.br
.ti -1c
.RI "std::string \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBtypes\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int argx::ARGXError::code"

.PP
Definition at line \fB21\fP of file \fBtypes\&.hpp\fP\&.
.SS "std::string argx::ARGXError::error"

.PP
Definition at line \fB18\fP of file \fBtypes\&.hpp\fP\&.
.SS "std::string argx::ARGXError::help"

.PP
Definition at line \fB19\fP of file \fBtypes\&.hpp\fP\&.
.SS "std::string argx::ARGXError::type"

.PP
Definition at line \fB17\fP of file \fBtypes\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Argx from the source code\&.
