.TH "inc/macros.hpp" 3 "Version 1.2.0-beta" "Argx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/macros.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBARGX_DEV\fP   false"
.br
.ti -1c
.RI "#define \fBARGX_PY_REQUIRED_VERSION_STD\fP   20250721"
.br
.ti -1c
.RI "#define \fBARGX_STRINGIFY\fP(x)"
.br
.ti -1c
.RI "#define \fBARGX_TOSTRING\fP(x)"
.br
.ti -1c
.RI "#define \fBARGX_VERSION\fP   ((\fBARGX_VERSION_MAJOR\fP<<16)|(\fBARGX_VERSION_MINOR\fP<<8)|(\fBARGX_VERSION_PATCH\fP)|(\fBARGX_VERSION_STATE\fP << 24))"
.br
.ti -1c
.RI "#define \fBARGX_VERSION_CHECK\fP(\fBARGX_VERSION_MAJOR\fP,  \fBARGX_VERSION_MINOR\fP,  \fBARGX_VERSION_PATCH\fP,  \fBARGX_VERSION_STATE\fP)"
.br
.ti -1c
.RI "#define \fBARGX_VERSION_MAJOR\fP   1"
.br
.ti -1c
.RI "#define \fBARGX_VERSION_MINOR\fP   2"
.br
.ti -1c
.RI "#define \fBARGX_VERSION_PATCH\fP   0"
.br
.ti -1c
.RI "#define \fBARGX_VERSION_STATE\fP   'beta'"
.br
.ti -1c
.RI "#define \fBARGX_VERSION_STD\fP   20250903"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ARGX_DEV   false"

.PP
Definition at line \fB33\fP of file \fBmacros\&.hpp\fP\&.
.SS "#define ARGX_PY_REQUIRED_VERSION_STD   20250721"

.PP
Definition at line \fB14\fP of file \fBmacros\&.hpp\fP\&.
.SS "#define ARGX_STRINGIFY( x)"
\fBValue:\fP
.nf
#x
.PP
.fi

.PP
Definition at line \fB36\fP of file \fBmacros\&.hpp\fP\&.
.SS "#define ARGX_TOSTRING( x)"
\fBValue:\fP
.nf
ARGX_STRINGIFY(x)
.PP
.fi

.PP
Definition at line \fB37\fP of file \fBmacros\&.hpp\fP\&.
.SS "#define ARGX_VERSION   ((\fBARGX_VERSION_MAJOR\fP<<16)|(\fBARGX_VERSION_MINOR\fP<<8)|(\fBARGX_VERSION_PATCH\fP)|(\fBARGX_VERSION_STATE\fP << 24))"

.PP
Definition at line \fB27\fP of file \fBmacros\&.hpp\fP\&.
.SS "#define ARGX_VERSION_CHECK( \fBARGX_VERSION_MAJOR\fP,  \fBARGX_VERSION_MINOR\fP,  \fBARGX_VERSION_PATCH\fP,  \fBARGX_VERSION_STATE\fP)"
\fBValue:\fP
.nf
    (((ARGX_VERSION_MAJOR)<<16)|((ARGX_VERSION_MINOR)<<8)|(ARGX_VERSION_PATCH)|((ARGX_VERSION_STATE) << 24))
.PP
.fi

.PP
Definition at line \fB29\fP of file \fBmacros\&.hpp\fP\&.
.nf
29 #define ARGX_VERSION_CHECK(ARGX_VERSION_MAJOR, ARGX_VERSION_MINOR, ARGX_VERSION_PATCH, ARGX_VERSION_STATE) \\
30     (((ARGX_VERSION_MAJOR)<<16)|((ARGX_VERSION_MINOR)<<8)|(ARGX_VERSION_PATCH)|((ARGX_VERSION_STATE) << 24))
.PP
.fi

.SS "#define ARGX_VERSION_MAJOR   1"

.PP
Definition at line \fB9\fP of file \fBmacros\&.hpp\fP\&.
.SS "#define ARGX_VERSION_MINOR   2"

.PP
Definition at line \fB10\fP of file \fBmacros\&.hpp\fP\&.
.SS "#define ARGX_VERSION_PATCH   0"

.PP
Definition at line \fB11\fP of file \fBmacros\&.hpp\fP\&.
.SS "#define ARGX_VERSION_STATE   'beta'"

.PP
Definition at line \fB22\fP of file \fBmacros\&.hpp\fP\&.
.SS "#define ARGX_VERSION_STD   20250903"

.PP
Definition at line \fB13\fP of file \fBmacros\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Argx from the source code\&.
