.TH "inc/types.hpp" 3 "Version 1.2.2-build" "Argx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/types.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBargx::ARGXError\fP"
.br
.ti -1c
.RI "struct \fBargx::ARGXOptions\fP"
.br
.ti -1c
.RI "struct \fBargx::ARGXParam\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBargx\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct argx::ARGXError \fBargx::ARGXError\fP"
.br
.ti -1c
.RI "typedef struct argx::ARGXOptions \fBargx::ARGXOptions\fP"
.br
.ti -1c
.RI "typedef struct argx::ARGXParam \fBargx::ARGXParam\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBargx::ARGXStyle\fP { \fBargx::Professional\fP, \fBargx::Simple\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Argx from the source code\&.
