src/core/FSI_dirUtils.c File Reference
#include "cstr/cstr.h"
#include "../../inc/fsi/FSIpredefines.h"
#include "../../inc/fsi/core/FSI_dirUtils.h"
#include "../../inc/fsi/core/interfaces/FSI_dirUtils_posix.h"
Functions
void fsi_walk (CVEC *vec, const char *path)
Walk to every directory and file and set vec to a CVEC value.
Function Documentation
fsi_walk()
void fsi_walk (CVEC * vec, const char * path)
Walk to every directory and file and set vec to a CVEC value.
Parameters
vec The vector to set data to
path Path to walk to all its sub-dirs
Definition at line 12 of file FSI_dirUtils.c.
{
    FSI_DirData dir;
    FSI_EntryData entry;
    if (!fsi_openDir(&dir, path))
        return;
    CSTR tmpPath = cstr_init();
    while (fsi_readDir(&dir, &entry))
    {
        cstr_set(&tmpPath, path);
        cstr_add(&tmpPath, "/");
        cstr_add(&tmpPath, entry.name);
        cvec_push(vec, const char*, CVEC_sys_strdup(tmpPath.data));
        if (entry.type == FSI_DIR)
            fsi_walk(vec, tmpPath.data);
    }
    cstr_destroy(&tmpPath);
    fsi_closeDir(&dir);
}
References fsi_closeDir(), FSI_DIR, fsi_openDir(), fsi_readDir(), fsi_walk(), FSI_EntryData::name, and FSI_EntryData::type.
Referenced by fsi::Indexer::__iteratePath(), and fsi_walk().