inc/fsi/core/FSI_dirUtils.h File Reference
#include "../FSIpredefines.h"
#include <string.h>
#include "cvec/cvec.h"
Classes
struct FSI_DirData
struct FSI_EntryData
Macros
#define __FSI_DIRUTILS_CPP_CLOSE }
#define __FSI_DIRUTILS_CPP_OPEN extern "C" {
Typedefs
typedef struct FSI_DirData FSI_DirData
typedef struct FSI_EntryData FSI_EntryData
typedef enum FSI_Type FSI_Type
Enumerations
enum FSI_Type { FSI_FILE
, FSI_DIR
, FSI_SYMLINK
, FSI_OTHER
 }
Functions
void fsi_walk (CVEC *vec, const char *path)
Walk to every directory and file and set vec to a CVEC value.
Macro Definition Documentation
__FSI_DIRUTILS_CPP_CLOSE
#define __FSI_DIRUTILS_CPP_CLOSE }
Definition at line 6 of file FSI_dirUtils.h.
__FSI_DIRUTILS_CPP_OPEN
#define __FSI_DIRUTILS_CPP_OPEN extern "C" {
Definition at line 5 of file FSI_dirUtils.h.
Typedef Documentation
FSI_DirData
typedef struct FSI_DirData FSI_DirData
FSI_EntryData
typedef struct FSI_EntryData FSI_EntryData
FSI_Type
typedef enum FSI_Type FSI_Type
Enumeration Type Documentation
FSI_Type
enum FSI_Type
Enumerator
FSI_FILE
FSI_DIR
FSI_SYMLINK
FSI_OTHER
Definition at line 20 of file FSI_dirUtils.h.
{
    FSI_FILE,
    FSI_DIR,
    FSI_SYMLINK,
    FSI_OTHER
} FSI_Type;
Function Documentation
fsi_walk()
void fsi_walk (CVEC * vec, const char * path)
Walk to every directory and file and set vec to a CVEC value.
Parameters
vec The vector to set data to
path Path to walk to all its sub-dirs
Definition at line 12 of file FSI_dirUtils.c.
{
    FSI_DirData dir;
    FSI_EntryData entry;
    if (!fsi_openDir(&dir, path))
        return;
    CSTR tmpPath = cstr_init();
    while (fsi_readDir(&dir, &entry))
    {
        cstr_set(&tmpPath, path);
        cstr_add(&tmpPath, "/");
        cstr_add(&tmpPath, entry.name);
        cvec_push(vec, const char*, CVEC_sys_strdup(tmpPath.data));
        if (entry.type == FSI_DIR)
            fsi_walk(vec, tmpPath.data);
    }
    cstr_destroy(&tmpPath);
    fsi_closeDir(&dir);
}
References fsi_closeDir(), FSI_DIR, fsi_openDir(), fsi_readDir(), fsi_walk(), FSI_EntryData::name, and FSI_EntryData::type.
Referenced by fsi::Indexer::__iteratePath(), and fsi_walk().