ciof Namespace Reference
Namespaces
namespace impl
Implementation functions.
Classes
struct CIOFOutputConfig
Set output configuration for ciof::impl::__out() function and its wrappers.
Typedefs
typedef struct ciof::CIOFOutputConfig CIOFOutputConfig
Set output configuration for ciof::impl::__out() function and its wrappers.
Enumerations
enum class OutputStyle { Bold
, Italic
, Underline
, Strikethrough
 }
Set output style: Bold Italic Underline Strikethrough.
enum class OutputType { Out
, Err
, Log
 }
Set output type for ciof::impl::__out() function and its helper functions Out : To Standard Output Err : To Standard Error Log : To Standard Log (Error, unbuffered).
Functions
void clear ()
Clear the contents of the terminal NOTE: In Windows; enable ANSI by doing ciof::initANSI().
std::string colorSet (int _color)
Set the colors from the default color palette from the terminal.
void cursorPos (int _row, int _col)
Get the set cursor position using _row and _col Essentially calls the getCursorPos() function and then sets the row and col according to the getCursorPos() function.
template<typename T>
void echo (T _t)
Echo to the standard output for _t.
template<typename T, typename ... Args>
void echo (T _t, Args ... _args)
Echo to the standard output for _t.
template<typename T>
void echoError (T _t)
Echo to the standard error for _t.
template<typename T, typename ... Args>
void echoError (T _t, Args ... _args)
Echo to the standard log for _t.
template<typename T>
void echoLog (T _t)
Echo to the standard log for _t.
template<typename T, typename ... Args>
void echoLog (T _t, Args ... _args)
Echo to the standard log for _t.
template<typename T, typename ... Args>
std::string format (T _t, Args ... _args)
Get everything as a string format.
std::string getCursorPos (int _row, int _col)
Get the set cursor position using _row and _col.
void initANSI ()
Initialize ANSI text option in Windows 10 or later NOTE: ONLY WORKS IN WINDOWS 10 OR LATER.
void input ()
Empty input() function; Do not save any input to a variable, just leave it as a blank input.
template<typename T>
void input (const std::string &_prompt, T *_var)
Get full input from the user with a prompt.
template<typename T>
void input (T *_var)
Get full input from the user.
void print ()
Print a new line.
template<typename T>
void print (T _t)
Print to the standard output for _t.
template<typename T, typename ... Args>
void print (T _t, Args ... _args)
Print to the standard output for _t.
template<typename T>
void printError (T _t)
Print to the standard error for _t.
template<typename T, typename ... Args>
void printError (T _t, Args ... _args)
Print to the standard error for _t.
template<typename T>
void printLog (T _t)
Print to the standard log for _t.
template<typename T, typename ... Args>
void printLog (T _t, Args ... _args)
Print to the standard log for _t.
std::string rgbBgSet (unsigned int r, unsigned int g, unsigned int b)
Set the RGB color for background in the terminal.
std::string rgbSet (unsigned int r, unsigned int g, unsigned int b)
Set the RGB color in the terminal.
void showCursor (const bool &show)
Show or hide the cursor from the terminal NOTE: In Windows; enable ANSI by doing ciof::initANSI().
std::string styleReset ()
Reset all the styles and colors in the terminal.
std::string styleSet (const OutputStyle &_style)
Set the styles according to the OutputStyle type.
Variables
CIOFOutputConfig outputConf
Set default output configuration.
Typedef Documentation
CIOFOutputConfig
typedef struct ciof::CIOFOutputConfig ciof::CIOFOutputConfig
Set output configuration for ciof::impl::__out() function and its wrappers.
Enumeration Type Documentation
OutputStyle
enum class ciof::OutputStyle [strong]
Set output style: Bold Italic Underline Strikethrough.
Enumerator
Bold
Italic
Underline
Strikethrough
Definition at line 58 of file ciof.hpp.
    {
        Bold,
        Italic,
        Underline,
        Strikethrough
    };
OutputType
enum class ciof::OutputType [strong]
Set output type for ciof::impl::__out() function and its helper functions Out : To Standard Output Err : To Standard Error Log : To Standard Log (Error, unbuffered).
Enumerator
Out
Err
Log
Definition at line 44 of file ciof.hpp.
    {
        Out, // std::cout
        Err, // std::cerr
        Log, // std::clog
    };
Function Documentation
clear()
void ciof::clear ()
Clear the contents of the terminal NOTE: In Windows; enable ANSI by doing ciof::initANSI().
Definition at line 64 of file ciof.cpp.
    { ciof::echo("\033[2J\033[H"); }
References echo().
colorSet()
std::string ciof::colorSet (int _color)
Set the colors from the default color palette from the terminal.
Parameters
_color Integer for color
Returns
std::string Escape code to set the code
Definition at line 76 of file ciof.cpp.
    { return "\033[" + std::to_string(_color) + "m"; }
cursorPos()
void ciof::cursorPos (int _row, int _col)
Get the set cursor position using _row and _col Essentially calls the getCursorPos() function and then sets the row and col according to the getCursorPos() function.
Parameters
_row Row to set (X)
_col Column to set (Y)
Definition at line 31 of file ciof.cpp.
    { std::cout << getCursorPos(_row, _col) << std::flush; }
References getCursorPos().
echo() [1/2]
template<typename T>
void ciof::echo (T _t)
Echo to the standard output for _t.
Parameters
_t Message to print
Referenced by clear(), and showCursor().
echo() [2/2]
template<typename T, typename ... Args>
void ciof::echo (T _t, Args ... _args)
Echo to the standard output for _t.
Parameters
_t Message to print
_args More messages to add
echoError() [1/2]
template<typename T>
void ciof::echoError (T _t)
Echo to the standard error for _t.
Parameters
_t Message to print
echoError() [2/2]
template<typename T, typename ... Args>
void ciof::echoError (T _t, Args ... _args)
Echo to the standard log for _t.
Parameters
_t Message to print
_args More messages to add
echoLog() [1/2]
template<typename T>
void ciof::echoLog (T _t)
Echo to the standard log for _t.
Parameters
_t Message to print
echoLog() [2/2]
template<typename T, typename ... Args>
void ciof::echoLog (T _t, Args ... _args)
Echo to the standard log for _t.
Parameters
_t Message to print
_args More messages to add
format()
template<typename T, typename ... Args>
std::string ciof::format (T _t, Args ... _args)
Get everything as a string format.
Parameters
_t First param of the string
_args Rest of the params of the string
Returns
std::string Return the formatted string
getCursorPos()
std::string ciof::getCursorPos (int _row, int _col)
Get the set cursor position using _row and _col.
Parameters
_row Row to set (X)
_col Column to set (Y)
Returns
std::string Return the string to set the position using ANSI
Definition at line 28 of file ciof.cpp.
    { return std::string("\033[" + std::to_string(_row) + ";" + std::to_string(_col) + "H"); }
Referenced by cursorPos().
initANSI()
void ciof::initANSI ()
Initialize ANSI text option in Windows 10 or later NOTE: ONLY WORKS IN WINDOWS 10 OR LATER.
Definition at line 34 of file ciof.cpp.
    {
# ifdef CIOF_OS_WIN32
        // NOTE:
        // This must ONLY be used in Windows 10 or newer
        if (!IsWindows10OrGreater()) return;
        
        HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
        DWORD dwMode = 0;
        GetConsoleMode(hOut, &dwMode);
        dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
        SetConsoleMode(hOut, dwMode);
# endif
    }
input() [1/3]
void ciof::input ()
Empty input() function; Do not save any input to a variable, just leave it as a blank input.
Definition at line 21 of file ciof.cpp.
    {
        std::string empty;
        ciof::input(&empty);
    }
References input().
Referenced by input().
input() [2/3]
template<typename T>
void ciof::input (const std::string & _prompt, T * _var)
Get full input from the user with a prompt.
Parameters
_prompt Prompt to user
_var Variable to store the value
input() [3/3]
template<typename T>
void ciof::input (T * _var)
Get full input from the user.
Parameters
_prompt Prompt to user
_var Variable to store the value
print() [1/3]
void ciof::print ()
Print a new line.
Definition at line 18 of file ciof.cpp.
    { std::cout << std::endl; }
print() [2/3]
template<typename T>
void ciof::print (T _t)
Print to the standard output for _t.
Parameters
_t Message to print
print() [3/3]
template<typename T, typename ... Args>
void ciof::print (T _t, Args ... _args)
Print to the standard output for _t.
Parameters
_t Message to print
_args More messages to add
printError() [1/2]
template<typename T>
void ciof::printError (T _t)
Print to the standard error for _t.
Parameters
_t Message to print
printError() [2/2]
template<typename T, typename ... Args>
void ciof::printError (T _t, Args ... _args)
Print to the standard error for _t.
Parameters
_t Message to print
_args More messages to add
printLog() [1/2]
template<typename T>
void ciof::printLog (T _t)
Print to the standard log for _t.
Parameters
_t Message to print
printLog() [2/2]
template<typename T, typename ... Args>
void ciof::printLog (T _t, Args ... _args)
Print to the standard log for _t.
Parameters
_t Message to print
_args More messages to add
rgbBgSet()
std::string ciof::rgbBgSet (unsigned int r, unsigned int g, unsigned int b)
Set the RGB color for background in the terminal.
Parameters
r Red color
g Green color
b Blue color
Returns
std::string Color escape sequence for RGB colors
Definition at line 86 of file ciof.cpp.
    {
        return "\033[48;2;" + std::to_string(r) + ";"
            + std::to_string(g) + ";"
            + std::to_string(b) + "m";
    }
rgbSet()
std::string ciof::rgbSet (unsigned int r, unsigned int g, unsigned int b)
Set the RGB color in the terminal.
Parameters
r Red color
g Green color
b Blue color
Returns
std::string Color escape sequence for RGB colors
Definition at line 79 of file ciof.cpp.
    {
        return "\033[38;2;" + std::to_string(r) + ";"
            + std::to_string(g) + ";"
            + std::to_string(b) + "m";
    }
showCursor()
void ciof::showCursor (const bool & show)
Show or hide the cursor from the terminal NOTE: In Windows; enable ANSI by doing ciof::initANSI().
Definition at line 67 of file ciof.cpp.
    {
        if (show) ciof::echo("\033[?25h");
        else ciof::echo("\033[?25l");
    }
References echo().
styleReset()
std::string ciof::styleReset ()
Reset all the styles and colors in the terminal.
Returns
std::string Escape code to ereset colors and styles from terminal
Definition at line 73 of file ciof.cpp.
    { return "\033[0m"; }
styleSet()
std::string ciof::styleSet (const OutputStyle & _style)
Set the styles according to the OutputStyle type.
Parameters
_style Set the style (Bold, Italics, Underline, ...)
Returns
std::string Escape code according to the style
Definition at line 52 of file ciof.cpp.
    {
        switch (_style)
        {
            case ciof::OutputStyle::Bold: return "\033[1m";
            case ciof::OutputStyle::Italic: return "\033[3m";
            case ciof::OutputStyle::Underline: return "\033[4m";
            case ciof::OutputStyle::Strikethrough: return "\033[9m";
            default: return "";
        }
    }
References Bold, Italic, Strikethrough, and Underline.
Variable Documentation
outputConf
CIOFOutputConfig ciof::outputConf
Set default output configuration.
Definition at line 16 of file ciof.cpp.