.TH "inc Directory Reference" 3 "Version 1.0.2-build" "Argx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArgx\&.h\fP"
.br
.ti -1c
.RI "file \fBARGXAddError\&.h\fP"
.br
.ti -1c
.RI "file \fBmacros\&.h\fP"
.br
.ti -1c
.RI "file \fBtypes\&.h\fP"
.br
.in -1c
