.TH "ArgxcErrorPair" 3 "Version 1.0.2-build" "Argx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArgxcErrorPair
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ARGXAddError\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBerror\fP"
.br
.ti -1c
.RI "const char * \fBhelp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBARGXAddError\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "const char* ArgxcErrorPair::error"

.PP
Definition at line \fB16\fP of file \fBARGXAddError\&.h\fP\&.
.PP
Referenced by \fBargxcGetErrorPair()\fP\&.
.SS "const char* ArgxcErrorPair::help"

.PP
Definition at line \fB17\fP of file \fBARGXAddError\&.h\fP\&.
.PP
Referenced by \fBargxcGetErrorPair()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Argx from the source code\&.
