.TH "ArgxcOptions" 3 "Version 1.0.2-build" "Argx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArgxcOptions
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBhasAnySubParams\fP"
.br
.ti -1c
.RI "bool \fBhasSubParams\fP"
.br
.ti -1c
.RI "char * \fBid\fP"
.br
.ti -1c
.RI "char * \fBinfo\fP"
.br
.ti -1c
.RI "char * \fBparam\fP"
.br
.ti -1c
.RI "char * \fBsparam\fP"
.br
.ti -1c
.RI "struct \fBArgxcOptions\fP * \fBsubParams\fP"
.br
.ti -1c
.RI "size_t \fBsubParamsCapacity\fP"
.br
.ti -1c
.RI "size_t \fBsubParamsCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB25\fP of file \fBtypes\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "bool ArgxcOptions::hasAnySubParams"

.PP
Definition at line \fB31\fP of file \fBtypes\&.h\fP\&.
.PP
Referenced by \fBargxcCompareArgs()\fP, \fBargxcCreateOption()\fP, and \fBargxcGetParam()\fP\&.
.SS "bool ArgxcOptions::hasSubParams"

.PP
Definition at line \fB30\fP of file \fBtypes\&.h\fP\&.
.PP
Referenced by \fBargxcCompareArgs()\fP, \fBargxcCreateDocs()\fP, \fBargxcCreateOption()\fP, and \fBargxcGetParam()\fP\&.
.SS "char* ArgxcOptions::id"

.PP
Definition at line \fB26\fP of file \fBtypes\&.h\fP\&.
.PP
Referenced by \fBargxcCreateDocs()\fP, \fBargxcCreateOption()\fP, \fBargxcFindParam()\fP, \fBargxcFreeOption()\fP, and \fBargxcGetParam()\fP\&.
.SS "char* ArgxcOptions::info"

.PP
Definition at line \fB29\fP of file \fBtypes\&.h\fP\&.
.PP
Referenced by \fBargxcCreateDocs()\fP, \fBargxcCreateOption()\fP, and \fBargxcFreeOption()\fP\&.
.SS "char* ArgxcOptions::param"

.PP
Definition at line \fB27\fP of file \fBtypes\&.h\fP\&.
.PP
Referenced by \fBargxcCompareArgs()\fP, \fBargxcCreateDocs()\fP, \fBargxcCreateOption()\fP, \fBargxcFindParam()\fP, \fBargxcFreeOption()\fP, and \fBargxcGetParam()\fP\&.
.SS "char* ArgxcOptions::sparam"

.PP
Definition at line \fB28\fP of file \fBtypes\&.h\fP\&.
.PP
Referenced by \fBargxcCompareArgs()\fP, \fBargxcCreateDocs()\fP, \fBargxcCreateOption()\fP, \fBargxcFindParam()\fP, \fBargxcFreeOption()\fP, and \fBargxcGetParam()\fP\&.
.SS "struct \fBArgxcOptions\fP* ArgxcOptions::subParams"

.PP
Definition at line \fB32\fP of file \fBtypes\&.h\fP\&.
.PP
Referenced by \fBargxcAddSubOption()\fP, \fBargxcCompareArgs()\fP, \fBargxcCreateDocs()\fP, \fBargxcCreateOption()\fP, \fBargxcFindParam()\fP, \fBargxcFreeOption()\fP, and \fBargxcGetParam()\fP\&.
.SS "size_t ArgxcOptions::subParamsCapacity"

.PP
Definition at line \fB34\fP of file \fBtypes\&.h\fP\&.
.PP
Referenced by \fBargxcAddSubOption()\fP, and \fBargxcFreeOption()\fP\&.
.SS "size_t ArgxcOptions::subParamsCount"

.PP
Definition at line \fB33\fP of file \fBtypes\&.h\fP\&.
.PP
Referenced by \fBargxcAddSubOption()\fP, \fBargxcCompareArgs()\fP, \fBargxcCreateDocs()\fP, \fBargxcCreateOption()\fP, \fBargxcFindParam()\fP, \fBargxcFreeOption()\fP, and \fBargxcGetParam()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Argx from the source code\&.
