.TH "ArgxcError" 3 "Version 1.0.2-build" "Argx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArgxcError
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcode\fP"
.br
.ti -1c
.RI "char * \fBerror\fP"
.br
.ti -1c
.RI "char * \fBhelp\fP"
.br
.ti -1c
.RI "char * \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBtypes\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int ArgxcError::code"

.PP
Definition at line \fB19\fP of file \fBtypes\&.h\fP\&.
.PP
Referenced by \fBargxcCreateError()\fP, \fBargxcCreateErrorSimple()\fP, and \fBargxcGetErrorCode()\fP\&.
.SS "char* ArgxcError::error"

.PP
Definition at line \fB17\fP of file \fBtypes\&.h\fP\&.
.PP
Referenced by \fBargxcCreateError()\fP, \fBargxcCreateErrorSimple()\fP, \fBargxcFreeError()\fP, \fBargxcGetErrorMessage()\fP, and \fBargxcGetErrorPair()\fP\&.
.SS "char* ArgxcError::help"

.PP
Definition at line \fB18\fP of file \fBtypes\&.h\fP\&.
.PP
Referenced by \fBargxcCreateError()\fP, \fBargxcCreateErrorSimple()\fP, \fBargxcFreeError()\fP, \fBargxcGetErrorHelp()\fP, and \fBargxcGetErrorPair()\fP\&.
.SS "char* ArgxcError::type"

.PP
Definition at line \fB16\fP of file \fBtypes\&.h\fP\&.
.PP
Referenced by \fBargxcCreateError()\fP, \fBargxcCreateErrorSimple()\fP, and \fBargxcFreeError()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Argx from the source code\&.
