.TH "Argxc" 3 "Version 1.0.2-build" "Argx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Argxc
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBid\fP"
.br
.ti -1c
.RI "unsigned int \fBmainArgc\fP"
.br
.ti -1c
.RI "char ** \fBmainArgs\fP"
.br
.ti -1c
.RI "size_t \fBmainArgsCount\fP"
.br
.ti -1c
.RI "\fBArgxcOptions\fP * \fBoptions\fP"
.br
.ti -1c
.RI "size_t \fBoptionsCapacity\fP"
.br
.ti -1c
.RI "size_t \fBoptionsCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBArgx\&.c\fP\&.
.SH "Field Documentation"
.PP 
.SS "char* Argxc::id"

.PP
Definition at line \fB16\fP of file \fBArgx\&.c\fP\&.
.PP
Referenced by \fBargxcCreate()\fP, \fBargxcCreateDefault()\fP, \fBargxcDestroy()\fP, and \fBargxcGetId()\fP\&.
.SS "unsigned int Argxc::mainArgc"

.PP
Definition at line \fB19\fP of file \fBArgx\&.c\fP\&.
.PP
Referenced by \fBargxcCreate()\fP, \fBargxcCreateDefault()\fP, \fBargxcGetArgc()\fP, and \fBargxcGetParam()\fP\&.
.SS "char** Argxc::mainArgs"

.PP
Definition at line \fB17\fP of file \fBArgx\&.c\fP\&.
.PP
Referenced by \fBargxcCreate()\fP, \fBargxcCreateDefault()\fP, \fBargxcDestroy()\fP, \fBargxcFindParam()\fP, \fBargxcGetMainArgs()\fP, and \fBargxcGetParam()\fP\&.
.SS "size_t Argxc::mainArgsCount"

.PP
Definition at line \fB18\fP of file \fBArgx\&.c\fP\&.
.PP
Referenced by \fBargxcCreate()\fP, \fBargxcCreateDefault()\fP, \fBargxcDestroy()\fP, \fBargxcFindParam()\fP, \fBargxcGetMainArgs()\fP, and \fBargxcGetParam()\fP\&.
.SS "\fBArgxcOptions\fP* Argxc::options"

.PP
Definition at line \fB20\fP of file \fBArgx\&.c\fP\&.
.PP
Referenced by \fBargxcAddOption()\fP, \fBargxcCreate()\fP, \fBargxcCreateDefault()\fP, \fBargxcCreateDocs()\fP, \fBargxcDestroy()\fP, \fBargxcFindParam()\fP, \fBargxcGetOptions()\fP, and \fBargxcGetParam()\fP\&.
.SS "size_t Argxc::optionsCapacity"

.PP
Definition at line \fB22\fP of file \fBArgx\&.c\fP\&.
.PP
Referenced by \fBargxcAddOption()\fP, \fBargxcCreate()\fP, and \fBargxcCreateDefault()\fP\&.
.SS "size_t Argxc::optionsCount"

.PP
Definition at line \fB21\fP of file \fBArgx\&.c\fP\&.
.PP
Referenced by \fBargxcAddOption()\fP, \fBargxcCreate()\fP, \fBargxcCreateDefault()\fP, \fBargxcCreateDocs()\fP, \fBargxcDestroy()\fP, \fBargxcFindParam()\fP, \fBargxcGetOptions()\fP, and \fBargxcGetParam()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Argx from the source code\&.
