.TH "vp" 3 "Version v1.0.0-build" "varpar.cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParser\fP"
.br
.ti -1c
.RI "struct \fBParserReturn\fP"
.br
.RI "Returned parser information This includes the configuration, output and success of the \fR\fBParser\fP\fP\&. "
.ti -1c
.RI "struct \fBParserStatus\fP"
.br
.RI "Set the error and if the \fR\fBParser\fP\fP class was constructed\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct vp::ParserReturn \fBParserReturn\fP"
.br
.RI "Returned parser information This includes the configuration, output and success of the \fR\fBParser\fP\fP\&. "
.ti -1c
.RI "typedef struct vp::ParserStatus \fBParserStatus\fP"
.br
.RI "Set the error and if the \fR\fBParser\fP\fP class was constructed\&. "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct vp::ParserReturn vp::ParserReturn"

.PP
Returned parser information This includes the configuration, output and success of the \fR\fBParser\fP\fP\&. 
.SS "typedef struct vp::ParserStatus vp::ParserStatus"

.PP
Set the error and if the \fR\fBParser\fP\fP class was constructed\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for varpar\&.cpp from the source code\&.
