.TH "inc/varparse.cpp/VP_Parse.hpp" 3 "Version v1.0.0-build" "varpar.cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/varparse.cpp/VP_Parse.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'VPpredefines\&.hpp'\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvp::Parser\fP"
.br
.ti -1c
.RI "struct \fBvp::ParserReturn\fP"
.br
.RI "Returned parser information This includes the configuration, output and success of the \fR\fBParser\fP\fP\&. "
.ti -1c
.RI "struct \fBvp::ParserStatus\fP"
.br
.RI "Set the error and if the \fR\fBParser\fP\fP class was constructed\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvp\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct vp::ParserReturn \fBvp::ParserReturn\fP"
.br
.RI "Returned parser information This includes the configuration, output and success of the \fR\fBParser\fP\fP\&. "
.ti -1c
.RI "typedef struct vp::ParserStatus \fBvp::ParserStatus\fP"
.br
.RI "Set the error and if the \fR\fBParser\fP\fP class was constructed\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for varpar\&.cpp from the source code\&.
