.TH "vp::ParserReturn" 3 "Version v1.0.0-build" "varpar.cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vp::ParserReturn \- Returned parser information This includes the configuration, output and success of the \fR\fBParser\fP\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <VP_Parse\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::map< std::string, std::string > \fBconfig\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBoutput\fP"
.br
.ti -1c
.RI "bool \fBsuccess\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Returned parser information This includes the configuration, output and success of the \fR\fBParser\fP\fP\&. 
.PP
Definition at line \fB26\fP of file \fBVP_Parse\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::map<std::string, std::string> vp::ParserReturn::config"

.PP
Definition at line \fB28\fP of file \fBVP_Parse\&.hpp\fP\&.
.SS "std::vector<std::string> vp::ParserReturn::output"

.PP
Definition at line \fB30\fP of file \fBVP_Parse\&.hpp\fP\&.
.SS "bool vp::ParserReturn::success = false"

.PP
Definition at line \fB32\fP of file \fBVP_Parse\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for varpar\&.cpp from the source code\&.
