.TH "vp::ParserStatus" 3 "Version v1.0.0-build" "varpar.cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vp::ParserStatus \- Set the error and if the \fR\fBParser\fP\fP class was constructed\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <VP_Parse\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBconstructed\fP = false"
.br
.ti -1c
.RI "std::string \fBerror\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Set the error and if the \fR\fBParser\fP\fP class was constructed\&. 
.PP
Definition at line \fB15\fP of file \fBVP_Parse\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool vp::ParserStatus::constructed = false"

.PP
Definition at line \fB19\fP of file \fBVP_Parse\&.hpp\fP\&.
.SS "std::string vp::ParserStatus::error"

.PP
Definition at line \fB17\fP of file \fBVP_Parse\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for varpar\&.cpp from the source code\&.
