.TH "src/Debug.cpp" 3 "Version 0.0.1-dev" "Pcannon Debug" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Debug.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <string>\fP
.br
\fR#include <filesystem>\fP
.br
\fR#include '\&.\&./inc/Debug\&.hpp'\fP
.br
\fR#include '\&.\&./vendor/cpp\-time\-utils/inc/Time\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpd\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pcannon Debug from the source code\&.
