.TH "inc/Debug.hpp" 3 "Version 0.0.1-dev" "Pcannon Debug" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/Debug.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <utility>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpd::Debug\fP"
.br
.ti -1c
.RI "struct \fBpd::DebugSettings\fP"
.br
.RI "Set debug settings struct with set values, default are already set for the best output\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpd\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct pd::DebugSettings \fBpd::DebugSettings\fP"
.br
.RI "Set debug settings struct with set values, default are already set for the best output\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Pcannon Debug from the source code\&.
