.TH "pd" 3 "Version 0.0.1-dev" "Pcannon Debug" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pd
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDebug\fP"
.br
.ti -1c
.RI "struct \fBDebugSettings\fP"
.br
.RI "Set debug settings struct with set values, default are already set for the best output\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct pd::DebugSettings \fBDebugSettings\fP"
.br
.RI "Set debug settings struct with set values, default are already set for the best output\&. "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct pd::DebugSettings pd::DebugSettings"

.PP
Set debug settings struct with set values, default are already set for the best output\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Pcannon Debug from the source code\&.
