.TH "pd::DebugSettings" 3 "Version 0.0.1-dev" "Pcannon Debug" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pd::DebugSettings \- Set debug settings struct with set values, default are already set for the best output\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Debug\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBblockedSave\fP = false"
.br
.ti -1c
.RI "bool \fBcustom\fP = false"
.br
.ti -1c
.RI "bool \fBdebugID\fP = true"
.br
.ti -1c
.RI "std::string \fBendMsg\fP"
.br
.ti -1c
.RI "std::string \fBfilePath\fP"
.br
.ti -1c
.RI "unsigned int \fBlogLevel\fP = 0"
.br
.ti -1c
.RI "bool \fBlogLevelIgnoreOutput\fP = false"
.br
.ti -1c
.RI "bool \fBlogLevelIgnoreSave\fP = false"
.br
.ti -1c
.RI "std::ios::openmode \fBopenMode\fP = std::fstream::app | std::fstream::in | std::fstream::out"
.br
.ti -1c
.RI "bool \fBoutput\fP = true"
.br
.ti -1c
.RI "std::string \fBpostEndMsg\fP"
.br
.ti -1c
.RI "std::string \fBpreStartMsg\fP"
.br
.ti -1c
.RI "std::string \fBstartMsg\fP"
.br
.ti -1c
.RI "bool \fBtimeStamp\fP = true"
.br
.ti -1c
.RI "bool \fBtimeZone\fP = false"
.br
.ti -1c
.RI "std::string \fBtotalCustom\fP"
.br
.ti -1c
.RI "std::string \fBtotalEndMsg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Set debug settings struct with set values, default are already set for the best output\&. 
.PP
Definition at line \fB21\fP of file \fBDebug\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool pd::DebugSettings::blockedSave = false"

.PP
Definition at line \fB27\fP of file \fBDebug\&.hpp\fP\&.
.SS "bool pd::DebugSettings::custom = false"

.PP
Definition at line \fB28\fP of file \fBDebug\&.hpp\fP\&.
.SS "bool pd::DebugSettings::debugID = true"

.PP
Definition at line \fB24\fP of file \fBDebug\&.hpp\fP\&.
.SS "std::string pd::DebugSettings::endMsg"

.PP
Definition at line \fB37\fP of file \fBDebug\&.hpp\fP\&.
.SS "std::string pd::DebugSettings::filePath"

.PP
Definition at line \fB34\fP of file \fBDebug\&.hpp\fP\&.
.SS "unsigned int pd::DebugSettings::logLevel = 0"

.PP
Definition at line \fB32\fP of file \fBDebug\&.hpp\fP\&.
.SS "bool pd::DebugSettings::logLevelIgnoreOutput = false"

.PP
Definition at line \fB29\fP of file \fBDebug\&.hpp\fP\&.
.SS "bool pd::DebugSettings::logLevelIgnoreSave = false"

.PP
Definition at line \fB30\fP of file \fBDebug\&.hpp\fP\&.
.SS "std::ios::openmode pd::DebugSettings::openMode = std::fstream::app | std::fstream::in | std::fstream::out"

.PP
Definition at line \fB42\fP of file \fBDebug\&.hpp\fP\&.
.SS "bool pd::DebugSettings::output = true"

.PP
Definition at line \fB26\fP of file \fBDebug\&.hpp\fP\&.
.SS "std::string pd::DebugSettings::postEndMsg"

.PP
Definition at line \fB38\fP of file \fBDebug\&.hpp\fP\&.
.SS "std::string pd::DebugSettings::preStartMsg"

.PP
Definition at line \fB36\fP of file \fBDebug\&.hpp\fP\&.
.SS "std::string pd::DebugSettings::startMsg"

.PP
Definition at line \fB35\fP of file \fBDebug\&.hpp\fP\&.
.SS "bool pd::DebugSettings::timeStamp = true"

.PP
Definition at line \fB23\fP of file \fBDebug\&.hpp\fP\&.
.SS "bool pd::DebugSettings::timeZone = false"

.PP
Definition at line \fB25\fP of file \fBDebug\&.hpp\fP\&.
.SS "std::string pd::DebugSettings::totalCustom"

.PP
Definition at line \fB40\fP of file \fBDebug\&.hpp\fP\&.
.SS "std::string pd::DebugSettings::totalEndMsg"

.PP
Definition at line \fB39\fP of file \fBDebug\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pcannon Debug from the source code\&.
