.TH "ciof::CIOFOutputConfig" 3 "Version v1.2.0-build" "CIOF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ciof::CIOFOutputConfig \- Set output configuration for \fBciof::impl::__out()\fP function and its wrappers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ciof\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBignoreAllFormating\fP = false"
.br
.ti -1c
.RI "bool \fBprocessing\fP = true"
.br
.ti -1c
.RI "bool \fBspacing\fP = false"
.br
.ti -1c
.RI "std::string \fBspacingDelimeter\fP = ' '"
.br
.in -1c
.SH "Detailed Description"
.PP 
Set output configuration for \fBciof::impl::__out()\fP function and its wrappers\&. 
.PP
Definition at line \fB23\fP of file \fBciof\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool ciof::CIOFOutputConfig::ignoreAllFormating = false"

.PP
Definition at line \fB29\fP of file \fBciof\&.hpp\fP\&.
.SS "bool ciof::CIOFOutputConfig::processing = true"

.PP
Definition at line \fB32\fP of file \fBciof\&.hpp\fP\&.
.SS "bool ciof::CIOFOutputConfig::spacing = false"

.PP
Definition at line \fB26\fP of file \fBciof\&.hpp\fP\&.
.SS "std::string ciof::CIOFOutputConfig::spacingDelimeter = ' '"

.PP
Definition at line \fB35\fP of file \fBciof\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CIOF from the source code\&.
