inc/fsi/core/interfaces/FSI_dirUtils_posix.h File Reference
#include "../../FSIpredefines.h"
#include "../FSI_dirUtils.h"
#include "cstr/cstr.h"
#include <dirent.h>
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>
Classes
struct FSI_DirData_POSIX
struct FSI_Visited_POSIX
Macros
#define __FSI_DIRUTILS_POSIX_CPP_CLOSE }
#define __FSI_DIRUTILS_POSIX_CPP_OPEN extern "C" {
Typedefs
typedef struct FSI_DirData_POSIX FSI_DirData_POSIX
typedef struct FSI_Visited_POSIX FSI_Visited_POSIX
Functions
static void __fsi_walk (CVEC *out, CVEC *visited, const char *path)
void fsi_closeDir (FSI_DirData *d)
Get the directory data to deallocate memory.
static FSI_EntryType fsi_getEntryType (int dirfd, struct dirent *e)
Get the entry type of the dirfd from the FSI_DirData_POSIX.
static FSI_EntryType fsi_getEntryTypeFromDirent (int dirfd, struct dirent *e, struct stat *stOut)
int fsi_openDir (FSI_DirData *d, const char *path)
Open directory as read only.
int fsi_readDir (FSI_DirData *d, FSI_EntryData *out)
Read directory from reading the FSI_DirData information.
static void fsi_visitedAdd (CVEC *v, dev_t dev, ino_t ino)
static int fsi_visitedHas (CVEC *v, dev_t dev, ino_t ino)
Macro Definition Documentation
__FSI_DIRUTILS_POSIX_CPP_CLOSE
#define __FSI_DIRUTILS_POSIX_CPP_CLOSE }
Definition at line 6 of file FSI_dirUtils_posix.h.
__FSI_DIRUTILS_POSIX_CPP_OPEN
#define __FSI_DIRUTILS_POSIX_CPP_OPEN extern "C" {
Definition at line 5 of file FSI_dirUtils_posix.h.
Typedef Documentation
FSI_DirData_POSIX
typedef struct FSI_DirData_POSIX FSI_DirData_POSIX
FSI_Visited_POSIX
typedef struct FSI_Visited_POSIX FSI_Visited_POSIX
Function Documentation
__fsi_walk()
void __fsi_walk (CVEC * out, CVEC * visited, const char * path) [inline], [static]
Definition at line 145 of file FSI_dirUtils_posix.h.
{
    int fd = open(path, O_RDONLY | O_DIRECTORY | O_CLOEXEC);
    if (fd < 0) return;
    DIR *dir = fdopendir(fd);
    if (!dir)
    {
        close(fd);
        return;
    }
    struct stat dirSt;
    if (fstat(fd, &dirSt) != 0)
    {
        closedir(dir);
        return;
    }
    if (fsi_visitedHas(visited, dirSt.st_dev, dirSt.st_ino))
    {
        closedir(dir);
        return;
    }
    fsi_visitedAdd(visited, dirSt.st_dev, dirSt.st_ino);
    struct dirent *e;
    CSTR tmp = cstr_init();
    while ((e = readdir(dir)))
    {
        if (e->d_name[0] == '.' &&
            (e->d_name[1] == '\0' || (e->d_name[1] == '.' && e->d_name[2] == '\0')))
            continue;
        struct stat st;
        int type = fsi_getEntryTypeFromDirent(fd, e, &st);
        cstr_set(&tmp, path);
        cstr_add(&tmp, "/");
        cstr_add(&tmp, e->d_name);
        cvec_push(out, const char*, CVEC_sys_strdup(tmp.data));
        if (type == FSI_DIR)
            __fsi_walk(out, visited, tmp.data);
    }
    cstr_destroy(&tmp);
    closedir(dir);
}
References __fsi_walk(), FSI_DIR, fsi_getEntryTypeFromDirent(), fsi_visitedAdd(), and fsi_visitedHas().
Referenced by __fsi_walk(), and fsi_walk().
fsi_closeDir()
void fsi_closeDir (FSI_DirData * d)
Get the directory data to deallocate memory.
Parameters
d Object to deallocate
Definition at line 41 of file FSI_dirUtils_posix.c.
{
    FSI_DirData_POSIX *p = d->impl;
    cstr_destroy(&p->path);
    // Closes FD variable too
    closedir(p->dir);
    FSI_FREE(p);
}
References FSI_DirData_POSIX::dir, FSI_FREE, FSI_DirData::impl, and FSI_DirData_POSIX::path.
fsi_getEntryType()
FSI_EntryType fsi_getEntryType (int dirfd, struct dirent * e) [inline], [static]
Get the entry type of the dirfd from the FSI_DirData_POSIX.
Get if: Directory, File, Symlink or other
Parameters
dirfd Entry type to get from the syscall
e Get dirent type quickly from the e ptr with its corresponding dirent data
Returns
Return the FSI_EntryType
Definition at line 70 of file FSI_dirUtils_posix.h.
{
    switch (e->d_type)
    {
        case DT_REG: return FSI_FILE;
        case DT_DIR: return FSI_DIR;
        case DT_LNK: return FSI_SYMLINK;
        case DT_UNKNOWN:
        default:
        {
            struct stat st;
            if (fstatat(dirfd, e->d_name, &st, AT_SYMLINK_NOFOLLOW) == 0)
            {
                if (S_ISREG(st.st_mode)) return FSI_FILE;
                if (S_ISDIR(st.st_mode)) return FSI_DIR;
                if (S_ISDIR(st.st_mode)) return FSI_SYMLINK;
            }
            return FSI_OTHER;
        }
    }
}
References FSI_DIR, FSI_FILE, FSI_OTHER, and FSI_SYMLINK.
fsi_getEntryTypeFromDirent()
FSI_EntryType fsi_getEntryTypeFromDirent (int dirfd, struct dirent * e, struct stat * stOut) [inline], [static]
Definition at line 94 of file FSI_dirUtils_posix.h.
{
    switch (e->d_type)
    {
        case DT_REG:
            return FSI_FILE;
        case DT_DIR:
            if (fstatat(dirfd, e->d_name, stOut, AT_SYMLINK_NOFOLLOW) == 0)
                return FSI_DIR;
            return FSI_OTHER;
        case DT_LNK: return FSI_SYMLINK;
        default:
            if (fstatat(dirfd, e->d_name, stOut, AT_SYMLINK_NOFOLLOW) == 0)
            {
                if (S_ISDIR(stOut->st_mode)) return FSI_DIR;
                if (S_ISREG(stOut->st_mode)) return FSI_FILE;
            }
            return FSI_OTHER;
    }
}
References FSI_DIR, FSI_FILE, FSI_OTHER, and FSI_SYMLINK.
Referenced by __fsi_walk().
fsi_openDir()
int fsi_openDir (FSI_DirData * d, const char * path)
Open directory as read only.
Parameters
d Directory data
path Path to open dir
Returns
Status (1 if worked, 0 if failed)
Definition at line 9 of file FSI_dirUtils_posix.c.
{
    const int dirFD = open(path, O_RDONLY | O_DIRECTORY | O_CLOEXEC);
    if (dirFD < 0) return 0;
    DIR *dir = fdopendir(dirFD);
    if (!dir)
    {
        close(dirFD);
        return 0;
    }
    FSI_DirData_POSIX *p = malloc(sizeof(*p));
    if (!p)
    {
        closedir(dir);
        return 0;
    }
    p->dir = dir;
    p->dirfd = dirFD;
    d->impl = p;
    return 1;
}
References FSI_DirData_POSIX::dir, FSI_DirData_POSIX::dirfd, and FSI_DirData::impl.
fsi_readDir()
int fsi_readDir (FSI_DirData * d, FSI_EntryData * out)
Read directory from reading the FSI_DirData information.
Parameters
d Directory data
out Entry data to set the information
Returns
Status (1 if worked, 0 if failed)
fsi_visitedAdd()
void fsi_visitedAdd (CVEC * v, dev_t dev, ino_t ino) [inline], [static]
Definition at line 135 of file FSI_dirUtils_posix.h.
{
    FSI_Visited_POSIX e = {0};
    e.dev = dev;
    e.ino = ino;
    cvec_push(v, FSI_Visited_POSIX, e);
}
References FSI_Visited_POSIX::dev, and FSI_Visited_POSIX::ino.
Referenced by __fsi_walk().
fsi_visitedHas()
int fsi_visitedHas (CVEC * v, dev_t dev, ino_t ino) [inline], [static]
Definition at line 120 of file FSI_dirUtils_posix.h.
{
    for (size_t i = 0 ; i < v->size ; i++)
    {
        FSI_Visited_POSIX *e = (FSI_Visited_POSIX*)cvec_get(v, i);
        
        if (!e) continue;
        if (e->dev == dev && e->ino == ino)
            return 1;
    }
    return 0;
}
References FSI_Visited_POSIX::dev, and FSI_Visited_POSIX::ino.
Referenced by __fsi_walk().