.TH "src/modules/temperature Directory Reference" 3 "Version v0.1.2-beta" "FileSystemIndexer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/temperature Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBFSI_temperature\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFSI_temperatureConverter\&.c\fP"
.br
.in -1c
