.TH "fsi::IndexerFoundInfo" 3 "Version v0.1.2-beta" "FileSystemIndexer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fsi::IndexerFoundInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FSI_Indexer\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBextension\fP"
.br
.ti -1c
.RI "std::string \fBextType\fP"
.br
.ti -1c
.RI "\fButils::TimeUtils_DateTime\fP \fBlastModDT\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::string \fBpath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB31\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string fsi::IndexerFoundInfo::extension"

.PP
Definition at line \fB35\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.SS "std::string fsi::IndexerFoundInfo::extType"

.PP
Definition at line \fB36\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.SS "\fButils::TimeUtils_DateTime\fP fsi::IndexerFoundInfo::lastModDT"

.PP
Definition at line \fB38\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.SS "std::string fsi::IndexerFoundInfo::name"

.PP
Definition at line \fB34\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.SS "std::string fsi::IndexerFoundInfo::path"

.PP
Definition at line \fB33\fP of file \fBFSI_Indexer\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileSystemIndexer from the source code\&.
