.TH "src/core/FSI_timeUtils.cpp" 3 "Version v0.1.2-beta" "FileSystemIndexer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/core/FSI_timeUtils.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./inc/fsi/core/FSI_timeUtils\&.hpp'\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <ctime>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBfsi\fP"
.br
.ti -1c
.RI "namespace \fBfsi::utils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTimeUtils_DateTime\fP \fBfsi::utils::fsClockDataToDT\fP (const fs::file_time_type &time)"
.br
.RI "Set std::filesystem clock data to an actual usable Date and Time format\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FileSystemIndexer from the source code\&.
