.TH "inc/fsi/core/FSI_dirUtils.h" 3 "Version v0.1.2-beta" "FileSystemIndexer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/fsi/core/FSI_dirUtils.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./FSIpredefines\&.h'\fP
.br
\fR#include 'cvec/cvec\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFSI_DirData\fP"
.br
.ti -1c
.RI "struct \fBFSI_EntryData\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__FSI_DIRUTILS_CPP_CLOSE\fP   }"
.br
.ti -1c
.RI "#define \fB__FSI_DIRUTILS_CPP_OPEN\fP   extern 'C' {"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct FSI_DirData \fBFSI_DirData\fP"
.br
.ti -1c
.RI "typedef struct FSI_EntryData \fBFSI_EntryData\fP"
.br
.ti -1c
.RI "typedef enum \fBFSI_EntryType\fP \fBFSI_EntryType\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFSI_EntryType\fP { \fBFSI_FILE\fP, \fBFSI_DIR\fP, \fBFSI_SYMLINK\fP, \fBFSI_OTHER\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfsi_walk\fP (CVEC *vec, const char *path)"
.br
.RI "Walk to every directory and file and set \fRvec\fP to a CVEC value\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __FSI_DIRUTILS_CPP_CLOSE   }"

.PP
Definition at line \fB6\fP of file \fBFSI_dirUtils\&.h\fP\&.
.SS "#define __FSI_DIRUTILS_CPP_OPEN   extern 'C' {"

.PP
Definition at line \fB5\fP of file \fBFSI_dirUtils\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct FSI_DirData FSI_DirData"

.SS "typedef struct FSI_EntryData FSI_EntryData"

.SS "typedef enum \fBFSI_EntryType\fP \fBFSI_EntryType\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBFSI_EntryType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIFSI_FILE \fP
.TP
\f(BIFSI_DIR \fP
.TP
\f(BIFSI_SYMLINK \fP
.TP
\f(BIFSI_OTHER \fP
.PP
Definition at line \fB18\fP of file \fBFSI_dirUtils\&.h\fP\&.
.nf
19 {
20     FSI_FILE,
21     FSI_DIR,
22     FSI_SYMLINK,
23     FSI_OTHER
24 } FSI_EntryType;
.PP
.fi

.SH "Function Documentation"
.PP 
.SS "void fsi_walk (CVEC * vec, const char * path)"

.PP
Walk to every directory and file and set \fRvec\fP to a CVEC value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvec\fP The vector to set data to 
.br
\fIpath\fP Path to walk to all its sub-dirs 
.RE
.PP

.PP
Definition at line \fB12\fP of file \fBFSI_dirUtils\&.c\fP\&.
.nf
13 {
14     CVEC visited = cvec_init(\-1, sizeof(FSI_Visited_POSIX*));
15 
16     __fsi_walk(out, &visited, path);
17 
18     cvec_destroy(&visited);
19 }
.PP
.fi

.PP
References \fB__fsi_walk()\fP\&.
.PP
Referenced by \fBfsi::Indexer::__iteratePath()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FileSystemIndexer from the source code\&.
