.TH "fsi::IndexerError" 3 "Version v0.1.0-beta" "FileSystemIndexer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fsi::IndexerError
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FSI_Indexer\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcode\fP = 0"
.br
.ti -1c
.RI "bool \fBfatal\fP = false"
.br
.ti -1c
.RI "std::string \fBmessage\fP"
.br
.ti -1c
.RI "bool \fBraise\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB49\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int fsi::IndexerError::code = 0"

.PP
Definition at line \fB53\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.PP
Referenced by \fBfsi::Indexer::addInfo()\fP, and \fBfsi::Indexer::removeInfo()\fP\&.
.SS "bool fsi::IndexerError::fatal = false"

.PP
Definition at line \fB55\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.PP
Referenced by \fBfsi::Indexer::addInfo()\fP, and \fBfsi::Indexer::removeInfo()\fP\&.
.SS "std::string fsi::IndexerError::message"

.PP
Definition at line \fB51\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.PP
Referenced by \fBfsi::Indexer::addInfo()\fP, and \fBfsi::Indexer::removeInfo()\fP\&.
.SS "bool fsi::IndexerError::raise = true"

.PP
Definition at line \fB56\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.PP
Referenced by \fBfsi::Indexer::addInfo()\fP, and \fBfsi::Indexer::removeInfo()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileSystemIndexer from the source code\&.
