.TH "src/core/interfaces/FSI_dirUtils_posix.c" 3 "Version v0.1.2-beta" "FileSystemIndexer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/core/interfaces/FSI_dirUtils_posix.c
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./\&.\&./inc/fsi/FSIpredefines\&.h'\fP
.br
\fR#include '\&.\&./\&.\&./\&.\&./inc/fsi/core/interfaces/FSI_dirUtils_posix\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfsi_closeDir\fP (\fBFSI_DirData\fP *d)"
.br
.RI "Get the directory data to deallocate memory\&. "
.ti -1c
.RI "int \fBfsi_openDir\fP (\fBFSI_DirData\fP *d, const char *path)"
.br
.RI "Open directory as read only\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void fsi_closeDir (\fBFSI_DirData\fP * d)"

.PP
Get the directory data to deallocate memory\&. 
.PP
\fBParameters\fP
.RS 4
\fId\fP Object to deallocate 
.RE
.PP

.PP
Definition at line \fB41\fP of file \fBFSI_dirUtils_posix\&.c\fP\&.
.nf
42 {
43     FSI_DirData_POSIX *p = d\->impl;
44 
45     cstr_destroy(&p\->path);
46 
47     // Closes FD variable too
48     closedir(p\->dir);
49 
50     FSI_FREE(p);
51 }
.PP
.fi

.PP
References \fBFSI_DirData_POSIX::dir\fP, \fBFSI_FREE\fP, \fBFSI_DirData::impl\fP, and \fBFSI_DirData_POSIX::path\fP\&.
.SS "int fsi_openDir (\fBFSI_DirData\fP * d, const char * path)"

.PP
Open directory as read only\&. 
.PP
\fBParameters\fP
.RS 4
\fId\fP Directory data 
.br
\fIpath\fP Path to open dir 
.RE
.PP
\fBReturns\fP
.RS 4
Status (1 if worked, 0 if failed) 
.RE
.PP

.PP
Definition at line \fB9\fP of file \fBFSI_dirUtils_posix\&.c\fP\&.
.nf
10 {
11     const int dirFD = open(path, O_RDONLY | O_DIRECTORY | O_CLOEXEC);
12 
13     if (dirFD < 0) return 0;
14 
15     DIR *dir = fdopendir(dirFD);
16 
17     if (!dir)
18     {
19         close(dirFD);
20 
21         return 0;
22     }
23 
24     FSI_DirData_POSIX *p = malloc(sizeof(*p));
25 
26     if (!p)
27     {
28         closedir(dir);
29 
30         return 0;
31     }
32 
33     p\->dir = dir;
34     p\->dirfd = dirFD;
35 
36     d\->impl = p;
37 
38     return 1;
39 }
.PP
.fi

.PP
References \fBFSI_DirData_POSIX::dir\fP, \fBFSI_DirData_POSIX::dirfd\fP, and \fBFSI_DirData::impl\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FileSystemIndexer from the source code\&.
