.TH "src/modules/temperature/FSI_temperature.cpp" 3 "Version v0.1.2-beta" "FileSystemIndexer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/temperature/FSI_temperature.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./\&.\&./inc/fsi/modules/temperature/FSI_temperature\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./\&.\&./inc/fsi/modules/temperature/FSI_temperatureConverter\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBfsi\fP"
.br
.ti -1c
.RI "namespace \fBfsi::modules\fP"
.br
.ti -1c
.RI "namespace \fBfsi::modules::tc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBfsi::modules::tc::convertFrom\fP (const std::string &to, const double &from)"
.br
.RI "Wrapper for \fR\fBFSI_temperatureConvertCelFrom()\fP\fP function\&. "
.ti -1c
.RI "double \fBfsi::modules::tc::convertTo\fP (const std::string &from, const double &to)"
.br
.RI "Wrapper for \fR\fBFSI_temperatureConvertCelTo()\fP\fP function\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FileSystemIndexer from the source code\&.
