.TH "FSI_Visited_POSIX" 3 "Version v0.1.2-beta" "FileSystemIndexer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSI_Visited_POSIX
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FSI_dirUtils_posix\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "dev_t \fBdev\fP"
.br
.ti -1c
.RI "ino_t \fBino\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB35\fP of file \fBFSI_dirUtils_posix\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "dev_t FSI_Visited_POSIX::dev"

.PP
Definition at line \fB37\fP of file \fBFSI_dirUtils_posix\&.h\fP\&.
.PP
Referenced by \fBfsi_visitedAdd()\fP, and \fBfsi_visitedHas()\fP\&.
.SS "ino_t FSI_Visited_POSIX::ino"

.PP
Definition at line \fB38\fP of file \fBFSI_dirUtils_posix\&.h\fP\&.
.PP
Referenced by \fBfsi_visitedAdd()\fP, and \fBfsi_visitedHas()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileSystemIndexer from the source code\&.
