.TH "inc/fsi/core/interfaces/FSI_dirUtils_windows.h" 3 "Version v0.1.2-beta" "FileSystemIndexer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/fsi/core/interfaces/FSI_dirUtils_windows.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./FSIpredefines\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__FSI_DIRUTILS_WINDOWS_CPP_CLOSE\fP   }"
.br
.ti -1c
.RI "#define \fB__FSI_DIRUTILS_WINDOWS_CPP_OPEN\fP   extern 'C' {"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __FSI_DIRUTILS_WINDOWS_CPP_CLOSE   }"

.PP
Definition at line \fB6\fP of file \fBFSI_dirUtils_windows\&.h\fP\&.
.SS "#define __FSI_DIRUTILS_WINDOWS_CPP_OPEN   extern 'C' {"

.PP
Definition at line \fB5\fP of file \fBFSI_dirUtils_windows\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FileSystemIndexer from the source code\&.
