.TH "src/core/FSI_dirUtils.c" 3 "Version v0.1.2-beta" "FileSystemIndexer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/core/FSI_dirUtils.c
.SH SYNOPSIS
.br
.PP
\fR#include 'cstr/cstr\&.h'\fP
.br
\fR#include '\&.\&./\&.\&./inc/fsi/FSIpredefines\&.h'\fP
.br
\fR#include '\&.\&./\&.\&./inc/fsi/core/FSI_dirUtils\&.h'\fP
.br
\fR#include '\&.\&./\&.\&./inc/fsi/core/interfaces/FSI_dirUtils_posix\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfsi_walk\fP (CVEC *out, const char *path)"
.br
.RI "Walk to every directory and file and set \fRvec\fP to a CVEC value\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void fsi_walk (CVEC * vec, const char * path)"

.PP
Walk to every directory and file and set \fRvec\fP to a CVEC value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvec\fP The vector to set data to 
.br
\fIpath\fP Path to walk to all its sub-dirs 
.RE
.PP

.PP
Definition at line \fB12\fP of file \fBFSI_dirUtils\&.c\fP\&.
.nf
13 {
14     CVEC visited = cvec_init(\-1, sizeof(FSI_Visited_POSIX*));
15 
16     __fsi_walk(out, &visited, path);
17 
18     cvec_destroy(&visited);
19 }
.PP
.fi

.PP
References \fB__fsi_walk()\fP\&.
.PP
Referenced by \fBfsi::Indexer::__iteratePath()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FileSystemIndexer from the source code\&.
