.TH "FSI_DirData" 3 "Version v0.1.2-beta" "FileSystemIndexer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSI_DirData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FSI_dirUtils\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBimpl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB26\fP of file \fBFSI_dirUtils\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "void* FSI_DirData::impl"

.PP
Definition at line \fB28\fP of file \fBFSI_dirUtils\&.h\fP\&.
.PP
Referenced by \fBfsi_closeDir()\fP, and \fBfsi_openDir()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileSystemIndexer from the source code\&.
