.TH "fsi::IndexerInfo" 3 "Version v0.1.0-beta" "FileSystemIndexer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fsi::IndexerInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FSI_Indexer\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBid\fP"
.br
.ti -1c
.RI "std::string \fBpath\fP"
.br
.ti -1c
.RI "\fBIndexerPathType\fP \fBpathType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB40\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string fsi::IndexerInfo::id"

.PP
Definition at line \fB42\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "std::string fsi::IndexerInfo::path"

.PP
Definition at line \fB43\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.PP
Referenced by \fBfsi::Indexer::addExtendedInfo()\fP, \fBfsi::Indexer::addInfo()\fP, \fBmain()\fP, and \fBfsi::Indexer::searchExactMatching()\fP\&.
.SS "\fBIndexerPathType\fP fsi::IndexerInfo::pathType"

.PP
Definition at line \fB46\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.PP
Referenced by \fBfsi::Indexer::addExtendedInfo()\fP, and \fBfsi::Indexer::addInfo()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileSystemIndexer from the source code\&.
