.TH "FSI_EntryData" 3 "Version v0.1.0-beta" "FileSystemIndexer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSI_EntryData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FSI_dirUtils\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBFSI_Type\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB33\fP of file \fBFSI_dirUtils\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const char* FSI_EntryData::name"

.PP
Definition at line \fB35\fP of file \fBFSI_dirUtils\&.h\fP\&.
.PP
Referenced by \fBfsi_readDir()\fP, and \fBfsi_walk()\fP\&.
.SS "\fBFSI_Type\fP FSI_EntryData::type"

.PP
Definition at line \fB37\fP of file \fBFSI_dirUtils\&.h\fP\&.
.PP
Referenced by \fBfsi_readDir()\fP, and \fBfsi_walk()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileSystemIndexer from the source code\&.
