.TH "fsi::utils::TimeUtils_DateTime" 3 "Version v0.1.0-beta" "FileSystemIndexer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fsi::utils::TimeUtils_DateTime
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FSI_timeUtils\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBday\fP"
.br
.ti -1c
.RI "unsigned int \fBhour\fP"
.br
.ti -1c
.RI "unsigned int \fBmin\fP"
.br
.ti -1c
.RI "unsigned int \fBmonth\fP"
.br
.ti -1c
.RI "unsigned int \fBms\fP"
.br
.ti -1c
.RI "unsigned int \fBsec\fP"
.br
.ti -1c
.RI "unsigned int \fByear\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBFSI_timeUtils\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int fsi::utils::TimeUtils_DateTime::day"

.PP
Definition at line \fB25\fP of file \fBFSI_timeUtils\&.hpp\fP\&.
.PP
Referenced by \fBanonymous_namespace{main\&.cpp}::__timeToStr()\fP, and \fBfsi::utils::fsClockDataToDT()\fP\&.
.SS "unsigned int fsi::utils::TimeUtils_DateTime::hour"

.PP
Definition at line \fB18\fP of file \fBFSI_timeUtils\&.hpp\fP\&.
.PP
Referenced by \fBanonymous_namespace{main\&.cpp}::__timeToStr()\fP, and \fBfsi::utils::fsClockDataToDT()\fP\&.
.SS "unsigned int fsi::utils::TimeUtils_DateTime::min"

.PP
Definition at line \fB19\fP of file \fBFSI_timeUtils\&.hpp\fP\&.
.PP
Referenced by \fBanonymous_namespace{main\&.cpp}::__timeToStr()\fP, and \fBfsi::utils::fsClockDataToDT()\fP\&.
.SS "unsigned int fsi::utils::TimeUtils_DateTime::month"

.PP
Definition at line \fB24\fP of file \fBFSI_timeUtils\&.hpp\fP\&.
.PP
Referenced by \fBanonymous_namespace{main\&.cpp}::__timeToStr()\fP, and \fBfsi::utils::fsClockDataToDT()\fP\&.
.SS "unsigned int fsi::utils::TimeUtils_DateTime::ms"

.PP
Definition at line \fB21\fP of file \fBFSI_timeUtils\&.hpp\fP\&.
.PP
Referenced by \fBanonymous_namespace{main\&.cpp}::__timeToStr()\fP, and \fBfsi::utils::fsClockDataToDT()\fP\&.
.SS "unsigned int fsi::utils::TimeUtils_DateTime::sec"

.PP
Definition at line \fB20\fP of file \fBFSI_timeUtils\&.hpp\fP\&.
.PP
Referenced by \fBanonymous_namespace{main\&.cpp}::__timeToStr()\fP, and \fBfsi::utils::fsClockDataToDT()\fP\&.
.SS "unsigned int fsi::utils::TimeUtils_DateTime::year"

.PP
Definition at line \fB23\fP of file \fBFSI_timeUtils\&.hpp\fP\&.
.PP
Referenced by \fBanonymous_namespace{main\&.cpp}::__timeToStr()\fP, and \fBfsi::utils::fsClockDataToDT()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileSystemIndexer from the source code\&.
