.TH "fsi::codes" 3 "Version v0.1.2-beta" "FileSystemIndexer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fsi::codes
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr int \fBERROR_ADDITION_FAIL\fP = 1"
.br
.ti -1c
.RI "constexpr int \fBERROR_EMPTY_VALUE\fP = 4"
.br
.ti -1c
.RI "constexpr int \fBERROR_ERASE_FAIL\fP = 2"
.br
.ti -1c
.RI "constexpr int \fBERROR_INVALID_PATH\fP = 3"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int fsi::codes::ERROR_ADDITION_FAIL = 1\fR [constexpr]\fP"

.PP
Definition at line \fB18\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.PP
Referenced by \fBfsi::Indexer::addInfo()\fP\&.
.SS "int fsi::codes::ERROR_EMPTY_VALUE = 4\fR [constexpr]\fP"

.PP
Definition at line \fB21\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.PP
Referenced by \fBfsi::Indexer::removeInfo()\fP\&.
.SS "int fsi::codes::ERROR_ERASE_FAIL = 2\fR [constexpr]\fP"

.PP
Definition at line \fB19\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.SS "int fsi::codes::ERROR_INVALID_PATH = 3\fR [constexpr]\fP"

.PP
Definition at line \fB20\fP of file \fBFSI_Indexer\&.hpp\fP\&.
.PP
Referenced by \fBfsi::Indexer::addInfo()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FileSystemIndexer from the source code\&.
