.TH "fsi::modules" 3 "Version v0.1.2-beta" "FileSystemIndexer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fsi::modules
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FileSystemIndexer from the source code\&.
